### PR TITLE
Incorrect schema subject name when decoding Avro

### PR DESCRIPTION
**Pull request by theduderog**
AvroMessageDecoder is using the topic name for the subject when the "is.new.producer" setting is true.  It's supposed to be the other way around.

### CODE REVIEW

**Comment by Ishiihara** [comment]
@theduderog In schema registry, we used topic-key and topic-value as the subject when the new producer is used. Can you elaborate why it is supposed to be the other way? Do you see any issues with the current implementation?

**Comment by theduderog** [comment]
@Ishiihara, You use topic-key and topic-value unless "is.new.producer" is set in the config.  When that config option is set, you're supposed to use schema-name-key and schema-name-value.  This is how the producer works so consumers need to match that behavior.  

Also, for reference, see [the discussion with Ewen](https://groups.google.com/forum/#!msg/confluent-platform/00QdLDDySXI/gU2zrw32PhUJ)

**Comment by Ishiihara** [comment]
@theduderog The Encoder interface used by old producer doesn't carry the topic information, so we use the schema name as the subject name. If you take a look at the schema registry code, https://github.com/confluentinc/schema-registry/blob/master/avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDe.java#L60 is used by `KafkaAvroSerializer` and https://github.com/confluentinc/schema-registry/blob/master/avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerDe.java#L71 is used by `KafkaAvroEncoder`.

**Comment by theduderog** [comment]
I'm using Samza to do message production and in the Samza Serde, I do not have access to the topic information either.  So I need my Camus import to also use the schema name as the subject.

I'm not proposing a fundamental change.  The existing Confluent clients already support both naming conventions (topic-prefixed and schema name-prefixed).  The "is.new.producer" flag is used to choose which behavior you desire.  The issue here is that the "is.new.producer" logic is reversed in the Camus AvroMessageDecoder but works correctly elsewhere.

**Comment by Ishiihara** [comment]
@theduderog If the new producer is used, the subject is topic prefixed. Then in `AvroMessageDecoder`, shouldn't we use the topic prefixed scheme to get the subject?

**Comment by theduderog** [comment]
Ah...I must have misunderstood.  Will dig some more.  Thanks!

**Comment by theduderog** [comment]
@Ishiihara,

Thank you for your help and sorry for the confusion.  I had the wrong idea of the expected behavior for "is.new.producer" was.

**Pull request closed without merging**
