### PR TITLE
CamusWrapper changed to mutable object.

### PR DESCRIPTION
**Pull request by telescope7**
Modified CamusWrapper to be a mutable object to avoid new object creation for every record being pulled out of Kafka. This improves the decode speed significantly.

### CODE REVIEW

**Comment by ghost** [comment]
It looks like @telescope7 hasn't signed our **C**ontributor **L**icense **A**greement, yet.

Appreciation of efforts,

clabot

**Comment by telescope7** [comment]
[clabot:check]

**Comment by ghost** [comment]
@confluentinc It looks like @telescope7 just signed our Contributor License Agreement. :+1:

Always at your service,

clabot

**Comment by ewencp** [comment]
@telescope7 We'd like to avoid diverging from the upstream linkedin/camus repository. I think the bulk of this would be better targeted as a PR on that repository, and then we could apply the changes for the Confluent-specific AvroMessageDecoder when we merge in those changes.

**Comment by telescope7** [comment]
@ewencp That makes sense.  I have also opened a PR on the linkedin/camus repository for this change.  [https://github.com/linkedin/camus/pull/236]

**Pull request closed without merging**
