### PR TITLE
Added new decoder to support Plain String Events from Kafka

### PR DESCRIPTION
**Pull request by mvalleavila**
Added support to read plain String events. 
To use this decoder set the property `camus.message.decoder.class` to

``` properties
camus.message.decoder.class=com.keedio.camus.etl.kafka.coders.StringMessageDecoder
```

The events will be stored in HDFS as plain Strings, the timestamp used in the events will be the current timestamp of the system.

### CODE REVIEW

**Comment by ghost** [comment]
It looks like @mvalleavila hasn't signed our **C**ontributor **L**icense **A**greement, yet.

Appreciation of efforts,

clabot

**Comment by mvalleavila** [comment]
[clabot:check]

**Comment by ghost** [comment]
@confluentinc It looks like @mvalleavila just signed our Contributor License Agreement. :+1:

Always at your service,

clabot

**Comment by ewencp** [comment]
Camus is also [deprecated](http://docs.confluent.io/3.0.0/camus/docs/intro.html) from CP 3.0.0 on and we won't be making further changes. This looks like a change that might have been better targeted at the upstream repository before it was deprecated, but also looks like there was a mismatch on the target branch anyway.

**Pull request closed without merging**
